/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bizimungu' at '3/7/16 10:03 PM' with Gradle 2.6
 *
 * @author bizimungu, @date 3/7/16 10:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
