/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bizimungu' at '4/12/16 8:00 AM' with Gradle 2.9
 *
 * @author bizimungu, @date 4/12/16 8:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
